### ISSUE TITLE
There is no way to select a directory

### ISSUE THREAD

**Issue by troe** [HelpSeeker/Gyre#1]
Hi, I installed the package via Flatpak on Kubuntu 20.04 and Ubuntu 20.04, but there is no way to select a directory anywhere.

Output of information from the terminal (Ubuntu 20.04):
`flatpak run io.github.helpseeker.Gyre

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/serg/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Gtk-Message: 15:56:53.601: Failed to load module "canberra-gtk-module"

(gyre:2): Gtk-WARNING **: 15:57:43.918: GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER is not supported by GtkFileChooserNativePortal because portal is too old

(gyre:2): Gtk-WARNING **: 15:57:55.515: GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER is not supported by GtkFileChooserNativePortal because portal is too old`

**Comment by HelpSeeker** [comment]
Thank you for reporting the issue.
Unfortunately this is a problem with your distros as their portal packages are too old to work with Gyre. There are, however, two possible solutions you can try out:

1. Install flatpak from [Alexander Larsson's PPA](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak).
2. Poke holes into the sandbox by giving Gyre file system access (e.g. `flatpak override --user io.github.helpseeker.Gyre --filesystem=home` to give it access to your home directory). The warning will still get displayed, but it won't affect you.

**Comment by troe** [comment]
1. I installed Flatpak through this PPA.
2. It worked in Ubuntu, but not on Kubuntu.

**Comment by HelpSeeker** [comment]
If it doesn't work with the PPA version then poking holes in the sandbox is the only other way. I recommend [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) as an easy solution to manage Flatpak permissions.
