### ISSUE TITLE
Best coubs of the year

### ISSUE THREAD

**Issue by superpupervlad** [HelpSeeker/Gyre#2]
Hello, first of all I would like to thank you for the opportunity to archive coubs before coub shuts down. 

It would be great if you have time to add possibility to download best coubs of the years, e.g. https://coub.com/best/2021.

**Comment by HelpSeeker** [comment]
I'll look into it. Can't promise an implementation before the weekend though.

**Comment by HelpSeeker** [comment]
A basic implementation, but it should get the job done. Flatpak update will be available shortly. If you encounter any issues, please let me know.
